 - hosts: vagrant
   sudo: yes
   vars:
       - vhosts: "{{ hostvars[inventory_hostname].enabled_vhosts }}"
   vars_files:
       - vars/mysql.yml
       - vars/apache.yml
   pre_tasks: 
       - set_fact: 
            apache_vhosts: "{{ lookup('template', 'templates/apache_vhosts.j2')|from_yaml }}"
       - debug: msg= "booh {{ item }}"
         with_items: "{{ apache_vhosts }}"
   roles: 
       - { role: geerlingguy.mysql }
       - { role: geerlingguy.apache }
   tasks:
       - name: "Create Document Roots"
         file: path={{ item.documentroot }} state=directory owner=apache group=apache mode=0775 recurse=yes
         with_items: "{{ apache_vhosts }}"
